# Generated by Django 5.0.3 on 2024-03-22 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fund', '0005_transaction_delete_blockchain'),
    ]

    operations = [
    ]
